name = "Sigma SMP"
author = "Donkey Melons"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0476b165a01063010db81ae3c7b3435d03f7aeef6fb496751d63dc3294ab6f39"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
